### ISSUE TITLE
Release Net.Appclusive.PS.Client

### ISSUE THREAD

**Issue by rufer7** [Appclusive/Net.Appclusive.Net.Client#14]
**TODOs**
* [x] Verify psm1 and psd1 using [PSScriptAnalyzer](https://d-fens.ch/2016/09/16/howto-analyze-powershell-scripts-with-psscriptanalyzer/)
* [x] Check scripts in setup repository using [PSScriptAnalyzer](https://d-fens.ch/2016/09/16/howto-analyze-powershell-scripts-with-psscriptanalyzer/)
* [x] Release `Net.Appclusive.PS.Client`
  * [x] Release at GitHub
  * [x] PowerShell Gallery
  * [x] NuGet
* [x] Verify Installation manuals by installing module
* [x] Verify badge including link in README
