### ISSUE TITLE
Release Net.Appclusive.PS.Client 4.0.2

### ISSUE THREAD

**Issue by rufer7** [Appclusive/Net.Appclusive.Net.Client#17]
**TODOs**
* [x] Verify psm1 and psd1 using [PSScriptAnalyzer](https://d-fens.ch/2016/09/16/howto-analyze-powershell-scripts-with-psscriptanalyzer/)
* [x] Release `Net.Appclusive.PS.Client`
  * [x] Release at GitHub
  * [x] PowerShell Gallery
  * [x] NuGet
* [x] Verify badge including link in README
* [x] Adjust release notes in PowerShell Gallery
