### ISSUE TITLE
Enter-Server Cmdlet

### ISSUE THREAD

**Issue by rufer7** [Appclusive/Net.Appclusive.Net.Client#2]
**TODOs**

* [x] Create project `Net.Appclusive.Net.Client`
* [x] Create project `Net.Appclusive.Net.Client.Tests`
* [x] Create project `Net.Appclusive.PS.Client`
* [x] Create project `Net.Appclusive.PS.Client.Tests`
* [x] Setup project `Net.Appclusive.PS.Client`
* [x] Implement `Enter-Server` Cmdlet

See [`biz.dfch.CS.Abiquo.Client`](https://github.com/dfensgmbh/biz.dfch.CS.Abiquo.Client/) for details
